import time
import os
#Module Above

i=os.system('cls')# linux下用clean
time.sleep(0.4)
print("#####  #    #    #####")
print("   #    #  #     #"   )
print("  #       #      #### ")
print(" #        #      #   ")
print("#####     #      #   ")
time.sleep(0.4)
i=os.system('cls')
print("  #####  #    #    #####")
print("     #    #  #     #"   )
print("    #       #      #### ")
print("   #        #      #   ")
print("  #####     #      #   ")
time.sleep(0.4)
i=os.system('cls')
print("    #####  #    #    #####")
print("       #    #  #     #"   )
print("      #       #      #### ")
print("     #        #      #   ")
print("    #####     #      #   ")
time.sleep(0.4)
i=os.system('cls')
print("      #####  #    #    #####")
print("         #    #  #     #"   )
print("        #       #      #### ")
print("       #        #      #   ")
print("      #####     #      #   ")
time.sleep(0.4)
i=os.system('cls')
print("        #####  #    #    #####")
print("           #    #  #     #"   )
print("          #       #      #### ")
print("         #        #      #   ")
print("        #####     #      #   ")
time.sleep(0.4)
i=os.system('cls')
print("          #####  #    #    #####")
print("             #    #  #     #"   )
print("            #       #      #### ")
print("           #        #      #   ")
print("          #####     #      #   ")
